FileVersion = 1
Dependencies = {corlib = "*", PixelBeef = "*"}

[Project]
Name = "SampleGame"
TargetType = "BeefGUIApplication"
StartupObject = "SampleGame.Program"

[Configs.Debug.Win64]
CLibType = "Dynamic"
